// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
// A namespace for generated variants and helper functions.
export namespace ReactionEmoji {
  // These are the generated variant types for each variant of the tagged union.
  // One type is generated per variant and will be used in the `value` field of
  // the tagged union.
  export type ThumbsUp = { tag: "ThumbsUp" };
  export type Heart = { tag: "Heart" };
  export type Laugh = { tag: "Laugh" };
  export type Party = { tag: "Party" };
  export type Wow = { tag: "Wow" };
  export type Rocket = { tag: "Rocket" };

  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  export const ThumbsUp = { tag: "ThumbsUp" };
  export const Heart = { tag: "Heart" };
  export const Laugh = { tag: "Laugh" };
  export const Party = { tag: "Party" };
  export const Wow = { tag: "Wow" };
  export const Rocket = { tag: "Rocket" };

  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createSumType([
      new SumTypeVariant("ThumbsUp", AlgebraicType.createProductType([])),
      new SumTypeVariant("Heart", AlgebraicType.createProductType([])),
      new SumTypeVariant("Laugh", AlgebraicType.createProductType([])),
      new SumTypeVariant("Party", AlgebraicType.createProductType([])),
      new SumTypeVariant("Wow", AlgebraicType.createProductType([])),
      new SumTypeVariant("Rocket", AlgebraicType.createProductType([])),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: ReactionEmoji): void {
      ReactionEmoji.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): ReactionEmoji {
      return ReactionEmoji.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

// The tagged union or sum type for the algebraic type `ReactionEmoji`.
export type ReactionEmoji = ReactionEmoji.ThumbsUp | ReactionEmoji.Heart | ReactionEmoji.Laugh | ReactionEmoji.Party | ReactionEmoji.Wow | ReactionEmoji.Rocket;

export default ReactionEmoji;

